#ifndef PHYSICS_PROPERTIES_H
#define PHYSICS_PROPERTIES_H

#define WOOD_DENSITY			60.0f
#define WOOD_FRICTION			0.3f
#define WOOD_RESTITUTION		0.50f


#define WOODBLOCK_DENSITY		60.0f
#define WOODBLOCK_FRICTION		0.3f;
#define WOODBLOCK_RESTITUTION	0.50f;

#define STONEBLOCK_DENSITY		80.0f
#define STONEBLOCK_FRICTION		0.3f
#define STONEBLOCK_RESTITUTION	0.50f


#define GLASSBLOCK_DENSITY		80.00f
#define GLASSBLOCK_FRICTION		3.0f;
#define GLASSBLOCK_RESTITUTION	0.05f;

#define STONE_DENSITY			80.0f
#define STONE_FRICTION			0.3f
#define STONE_RESTITUTION		0.50f


#define GLASS_DENSITY			40.0f
#define GLASS_FRICTION			0.3f
#define GLASS_RESTITUTION		0.50f


#define REDBIRD_DENSITY			80.0f
#define REDBIRD_FRICTION		0.3f
#define REDBIRD_RESTITUTION		0.50f

#define YELLOWBIRD_DENSITY			80.0f
#define YELLOWBIRD_FRICTION			0.3f
#define YELLOWBIRD_RESTITUTION		0.50f

#define WHITEBIRD_DENSITY			120.0f
#define WHITEBIRD_FRICTION			0.3f
#define WHITEBIRD_RESTITUTION		0.50f

#define GREENBIRD_DENSITY			120.0f
#define GREENBIRD_FRICTION			0.3f
#define GREENBIRD_RESTITUTION		0.20f


#define BLUEBIRD_DENSITY			150.0f
#define BLUEBIRD_FRICTION			0.3f
#define BLUEBIRD_RESTITUTION		0.50f


#define PIG_DENSITY			    20.0f
#define PIG_FRICTION			0.3f
#define PIG_RESTITUTION		    0.50f


#define MEDPIG_DENSITY			20.0f;
#define MEDPIG_FRICTION			0.3f;
#define MEDPIG_RESTITUTION		0.50f;


#define DMGMULTIPLIER			10.0f;


#define STONE_HEALTH_PER_PIXEL  1.0f
#define WOOD_HEALTH_PER_PIXEL   0.5f
#define GLASS_HEALTH_PER_PIXEL  0.15f
#define PIG_HEALTH_PER_PIXEL    0.07f
#define MEDPIG_HEALTH_PER_PIXEL 0.07f

#define OTHERDENS = 20.0f


#endif